name: Deploy to Cloudflare

defaults:
  run:
    working-directory: apps/email-signature-parser

on:
  push:
    branches: [main]
    paths:
      - 'apps/email-signature-parser/**'
      - '.github/workflows/deploy-email-signature-parser.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clear Wrangler Cache
        run: wrangler logout

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          main: 'apps/email-signature-parser/src/index.ts'